### ISSUE TITLE
Config not updated when it has mixed levels

### ISSUE THREAD

**Issue by ryanmitchell** [Stillat/proteus#23]
We are using this library in the Statamic Mailchimp add-on, but there is an issue when saving the config: https://github.com/statamic-rad-pack/mailchimp/issues/100

The issue seems to be coming from [these lines in ConfigUpdater](https://github.com/Stillat/proteus/blob/d20a40d0935440a0a4cafad2b61a1622092ae928/src/ConfigUpdater.php#L278-L281) - in our case we are [passing an array of mixed levels](https://github.com/statamic-rad-pack/mailchimp/blob/main/config/mailchimp.php) (some with no children, some with children) and it only returns those with children.

If I comment those lines out, updating work fine.

Our code is pretty simple: `ConfigWriter::writeMany('mailchimp', $data);`

Are we doing something wrong, or is it a bug?

**Comment by JohnathonKoster** [comment]
This will take some time to review and fully debug, and see if a solution can be found. The highlighted lines cannot be removed with the way things are currently implemented.

**Comment by ryanmitchell** [comment]
Appreciate you looking into it - if you need anything else from me just let me know.
