### ISSUE TITLE
Suport for `php-parser` v5

### ISSUE THREAD

**Issue by duncanmcclean** [Stillat/proteus#33]
Otherwise... this package can't be used in apps with PHPUnit 11.

If this package didn't go totally over my head, I'd contribute a PR 😆

**Comment by JohnathonKoster** [comment]
To help set some expectations, this will likely be a new major version/bump on this one due to some under-the-hood changes 👍

**Comment by JohnathonKoster** [comment]
Available with major version 4.0.1. This version _only_ supports `php-parser` v5. For installations that need to use `php-parser` v4, please continue to version 3 for those.

**Comment by duncanmcclean** [comment]
Thanks John! 🎉
