### ISSUE TITLE
Error with overriding method

### ISSUE THREAD

**Issue by edalzell** [Stillat/proteus#6]
`Access level to Stillat\\Proteus\\Document\\Printer::hasNodeWithComments() must be protected (as in class PhpParser\\PrettyPrinter\\Standard) or weaker`

Getting this error due to this commit: https://github.com/nikic/PHP-Parser/commit/1d1bc8a36459d67acef508b952dad097960b110e.

This method in your package can be removed. There may be others, I'd check that commit.

I'll do a PR if I can.

**Comment by JohnathonKoster** [comment]
Awesome; thanks! I'll be able to check this out tomorrow 🙂

**Comment by JohnathonKoster** [comment]
Corrected with v1.0.5
